# Generated by Django 5.2.4 on 2025-08-07 12:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='session_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
